### ISSUE TITLE
JUST FOUND POOL FEE GOING TO DIFFERENT ADDRESSES

### ISSUE THREAD

**Issue by Racing1** [AlphaX-Projects/alphaxcore#10]
I have the pool wallet and fee wallet set as the same. Yet, all pool fees are getting sent to separate accounts that I do not own.
Anyone else having this happen???

**Comment by developer-yellowstudio** [comment]
Just had the same issue

**Comment by AlphaX-Projects** [comment]
Depends on which coin you running, like goldcash allways create a new address. It is a Wallet thing.

**Comment by developer-yellowstudio** [comment]
For Callisto, this issue has only happened since yesterday when I installed the new repo

**Comment by Racing1** [comment]
> Depends on which coin you running, like goldcash allways create a new address. It is a Wallet thing.

I am running Groestlcoin, Zcash, Raptoreum, Ring and Dash. All Solo mining and all pool fees are going to their respective wallets except GRS. GRS keeps sending the fee to different addresses. Do you know how to fix this?

**Comment by AlphaX-Projects** [comment]
I guess you need to create a Legacy Address

**Comment by Racing1** [comment]
Yes I reached out to the groestlcoin team and they figured it out. Thanks
for responding
