### ISSUE TITLE
Raptoreum mining

### ISSUE THREAD

**Issue by philipalive** [AlphaX-Projects/alphaxcore#19]
Hi!
Can core mine Raptoreum coins as is or should I add some code to support mining?
Is there any documentation how can I mine raptoreum coins?
I saw different blockchains in a project, but there is no one for raptoreum. Should there be added one for it?

**Comment by blockinator** [comment]
It supports it: https://github.com/AlphaX-Projects/alphaxcore/blob/master/examples/raptoreum_pool.json
